### ISSUE TITLE
Not possible to start multiple overlay applications set to run using steam:// URL method

### ISSUE THREAD

**Issue by BPHardware** [ValveSoftware/VR-Community-Bugs#12] opened 2018-07-23 00:39 UTC
The message below is copied directly from the user's post:
https://steamcommunity.com/app/250820/discussions/3/1708438376923439847/

From Joe's comments on the thread, appears to be Steam Client bug. User points to Virtual Desktop community thread as well:
https://steamcommunity.com/app/382110/discussions/0/2425614539580464980/#c2425614539581257379

*********
Currently impossible to run more than one overlay application if manifest file of app (or steamapps.vrmanifest) use "url" type of run (that's applications from Steam). There is no limitation if type of run is "binary" (that's applications not from Steam).

List of steps I took:

1. Installed overlays applications from Steam - TurnSignal (689580), Virtual Desktop Dashboard (783710), my (not published) application (908520).

2. 
Settings:
In file "steam.overlay.689580.vrappconfig": "autolaunch" : true
In file "steam.overlay.783710.vrappconfig": "autolaunch" : true
In file "steam.overlay.908520.vrappconfig": "autolaunch" : true
Result:
only my application is run with SteamVR.

3. 
Settings:
In file "steam.overlay.689580.vrappconfig": "autolaunch" : true
In file "steam.overlay.783710.vrappconfig": "autolaunch" : true
In file "steam.overlay.908520.vrappconfig": "autolaunch" : false
Result:
only TurnSignal (689580) is run with SteamVR.

4. 
Settings:
In file "steam.overlay.689580.vrappconfig": "autolaunch" : true
In file "steam.overlay.783710.vrappconfig": "autolaunch" : false
In file "steam.overlay.908520.vrappconfig": "autolaunch" : false
Result:
only Virtual Desktop Dashboard (783710) is run with SteamVR.

All other overlay applications not from Steam is run with SteamVR without this limitation.

**Comment by KWS-Compat** [comment] 2018-07-23 16:06
**SteamVR Dashboard Apps(Various): Autolaunch does not launch all properly configured applications**

We were unable to reproduce the reported issue using a variety of hardware.
The steps outlined by the reporter were followed and the issue did not occur during any of our testing.

Each title's steam.overlay.######.vrconfig file was edited to set autolaunch to true.
In all cases, every configured application automatically launched after SteamVR was started alone.

**Hardware Tested:**

```
Configuration 1:
Intel Core i7-4790K CPU
AMD Radeon R9 380 GPU
16GB RAM
```

```
Configuration 2:
Intel Core i7-8700K
NVDIA GeForce GTX 980
16GB RAM
```

```
Configuration 3:
AMD A10-7870K CPU
Nvidia 1050Ti GPU
8GB RAM
```

**Software tested:**
```
SteamVR Public-250820			(BuildID:2884151)
SteamVR Beta-250820			(BuildID:2967062)
OVR Drop-586210				(BuildID:1769147)
Virtual Desktop Dashboard-783710	(BuildID:2909531)
TurnSignal-689580 			(BuildID:2443281)
```



More information and context is needed to fully identify this issue.

**Comment by KWS-Compat** [comment] 2019-03-21 14:28
The issue was observed to no longer occur as of SteamVR Beta Build 1.3.16 and SteamVR Stable Build 1.2.10.

Following the repro steps above, we had 4 different Overlay applications' autolaunch setting to 'true' when SteamVR launches:
1. OpenVR Advanced Settings (V 2.5)
2. Virtual Desktop Dashboard (BuildID: 3596839)
3. OVR Drop (BuildID: 3640358)
4. TurnSignal (BuildID: 3232515)

Upon launch, all 4 overlay application were successfully booted and show up in SteamVR Overlay without any issue.

**Comment by sergioberg** [comment] 2019-07-22 16:45
The issue still occur(slightly different, but still exists) on any SteamVR versions.

The message below is my post:
https://steamcommunity.com/app/250820/discussions/3/1708438376923439847/

Tested apps:

1. TurnSignal (latest build on public branch)
2. fpsVR (build on "test_bug" branch(**only this branch use URL method**), start fpsVR manually at least once)

Configuration 1:
Intel Core i7-3770K CPU
NVDIA GeForce GTX 1070 GPU
24GB RAM
SSD

Configuration 2:
Intel Core i7-8700K CPU
NVDIA GeForce GTX 1080Ti GPU
32GB RAM
SSD

Average result on both system:

2/10 TurnSignal started, fpsVR not started
2/10 TurnSignal not started, fpsVR started
6/10 TurnSignal started, fpsVR started

**Comment by JoeLudwig** [comment] 2019-07-26 01:52
This will be fixed in the 1.7.1 version of SteamVR.

**Closed as completed by JoeLudwig** 2019-07-26 01:52 UTC

**Comment by sergioberg** [comment] 2019-08-06 14:27
> This will be fixed in the 1.7.1 version of SteamVR.

@JoeLudwig 
SteamVR beta 1.7.1 - not fixed, the issue still occur

**Comment by JoeLudwig** [comment] 2019-08-06 15:16
1.7.1 doesn't have everything from our main branch for Reasons. 1.7.2 should (and the fix is in the main branch, so whenever that merges over is when the fix will ship.)

**Comment by sergioberg** [comment] 2019-08-06 15:16
Thanks!
