### ISSUE TITLE
SteamVR is not reporting accurate playtime.  

### ISSUE THREAD

**Issue by BPHardware** [ValveSoftware/VR-Community-Bugs#4] opened 2018-06-26 22:36 UTC
Issue - SteamVR playtime is inaccurate and is adding more time then was actually spent in game.

OS/GPU drivers - Windows 10 stable (17134), Nvidia 398.11 

Steam Client/SteamVR Version - Duplicated with both stable and beta of SteamVR

VR Equipment/Software Version - Occurs on all HMDs 

Community Source Links -
https://steamcommunity.com/app/250820/discussions/3/1694920442958059736/

Repro Steps -

Run SteamVR for a set amount of time. Notice the recorded playtime is inaccurate. 

Expected - Playtime should reflect actual time played. 

Encountered - Recorded playtime is inaccurate. 

Additional notes:
We have had multiple reports from users experiencing this issue.

**Comment by KWS-Compat** [comment] 2018-07-11 14:18
Here are the results of our investigation:
**SteamVR**
  
This issue appears to display “hours played” to display the number of hours since SteamVR was first run on a config. 
- This issue does not appear to be affected by whether SteamVR is running or not.
- This issue does not appear to be affected by the config itself being powered on or off.
- Starting steam simply updates the new time since the time played was last checked.
  
**Repro Steps:**
1. Install SteamVR.
2. Play for a set amount of time to initialize the hours played counter.
3. Close SteamVR and soak the machine(either running or not) for a set amount of time. 
4. Launch Steam and observe hours played. 

**Expected Result:** Hours played only reflects active time SteamVR has been running.
**Encountered Result:** Hours played reflect the total real time since SteamVR was first run/installed.

**Repro Rate:** 3/5
  
**Config Details:** 
Issue does not appear to be CPU or GPU bound
- Tested on AMD Threadripper 1950X, AMD Ryzen 7 1700, Intel Core i7-4790K
- Tested on Radeon RX 480 MSI, NVIDIA GeForce GTX 1080
Issue does not appear to be related to OS as the 
- Issue continues to tick up on Linux configs however the issue may have been triggered originally on a windows config. 
- Additional testing on isolated accounts would be required to rule out OS as a factor.

**Build:**
- AppID: 250820
- App BuildID: 2894227

**Additional Notes:**
We have reproduced this on a few accounts but we believe this may have to do with how Steam determines whether an app is running. Our affected accounts display hours played that line up with our install dates.

We soaked 2 of our affected machines for 2 hours each and noted a 2 hour rise in both account's play times despite having SteamVR fully closed and one machine being off entirely.

**Comment by KWS-Compat** [comment] 2019-03-18 11:26
Issue no longer occurs as of SteamVR Beta Build 1.3.14159. The reported playtime is now affected by the behavior described in issue #135.

**Comment by kisak-valve** [comment] 2019-03-18 12:26
Closing per the last comment / https://github.com/ValveSoftware/VR-Community-Bugs/issues/135#issuecomment-473873503.

**Closed as completed by kisak-valve** 2019-03-18 12:26 UTC
